plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cleaner.subtitles'
    compileSdk 34

    defaultConfig {
        applicationId "com.cleaner.subtitles"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // Принудительно задаём имя итогового APK файла
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "SubtitleCleaner.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
